# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

format B 20 2 0
leftstring A0 = "name"
leftstring B0 = "Oko Michael Akpu"
leftstring A1 = "Age"
let B1 = 26
leftstring A2 = "Occupation"
leftstring B2 = "Software Engineering"
goto C7
